import assert from 'node:assert/strict';
import fs from 'node:fs';
import {TestCar,recognitionInput} from '../teste/physics.js';
import {RaceField} from '../teste/race-field.js';
const data=JSON.parse(fs.readFileSync(new URL('../dados/pista.json',import.meta.url))),L=data.meta.reconstructed_xy_m;
const surface=(s,d=0)=>({s,width:12,d});
let c=new TestCar(data);
c.trackLap(surface(100),surface(140,10),42,20);assert(c.lapValid);
c.trackLap(surface(140,10),surface(190,10),52,20);
c.trackLap(surface(190,10),surface(230),43,20);assert(c.lapValid,'running wide without cutting stays valid');
c.trackLap(surface(230),surface(250,9),22,20);c.trackLap(surface(250,9),surface(275),20,20);assert(c.lapValid,'minor apex excursion tolerated');
c.trackLap(surface(275),surface(300,20),22,20);c.trackLap(surface(300,20),surface(490),75,20);assert(!c.lapValid,'skipping a large part of the route invalidates');
const fullLap=car=>{let previous=surface(0);for(let s=5;s<L;s+=5){const current=surface(s);car.clock+=.1;car.trackLap(previous,current,5,50);previous=current;}car.trackLap(previous,surface(1),L-previous.s+1,50);};
fullLap(c);assert.equal(c.laps,0,'cut lap cannot finish the race');assert.equal(c.lastLapValid,false);assert.equal(c.best,null);
fullLap(c);assert.equal(c.laps,1);assert.equal(c.lastLapValid,true);assert(c.best>0);
fullLap(c);fullLap(c);assert.equal(c.laps,3);
c=new TestCar(data);c.trackLap(surface(L-5),surface(2),7,-4);assert.equal(c.laps,0,'reversing across finish never counts');
c.trackLap(surface(100),surface(550),450,50);c.trackLap(surface(L-5),surface(2),7,50);assert.equal(c.laps,0,'missing checkpoints never finishes');
const field=new RaceField(data);field.rivals[0].progress=L+1;field.step(c,1/120,3);assert(!field.rivals[0].finished,'rivals race past lap one');field.rivals[0].progress=3*L+1;field.step(c,1/120,3);assert(field.rivals[0].finished,'rivals finish after three laps');
const driven=new TestCar(data);for(let i=0;i<120*900&&driven.laps<3;i++)driven.step(recognitionInput(driven),1/120);assert.equal(driven.laps,3,'three actual simulated laps count correctly');
console.log('Laps passed: runoff, small excursions, actual shortcuts, invalid laps, recovery, reverse, checkpoints, three-lap rivals and three complete simulated laps.');
